### ISSUE TITLE
PackML-StateModel.png

### ISSUE THREAD

**Issue by runtimevic** [Spruik/PackML-MQTT-Simulator#19]
Hello,
Could you tell me what program you have drawn the diagram PackML-StateModel.png with or send it to me to edit it.
Thanks a lot, Víctor.

**Comment by tomhollingworth** [comment]
Hi @runtimevic we used draw.io

**Comment by runtimevic** [comment]
> Hi @runtimevic we used draw.io

Hi, 
thank you so much for answering.
